name = "pm-arigato"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV_INVOICES"
id = "1a257a6ae93f4954b291486f28e54854"
preview_id = "0dd248aa76ec4729927f5c84ae59ab1b"
